<section class="section bg-light py-5">
    <div class="container">

        <div class="row justify-content-center">
            <div class="col-lg-8">
                <div class="text-center mb-5">
                    <h1 class="mb-3 ff-secondary fw-semibold lh-base">AI Image Gallery</h1>
                    <p class="text-muted">Images generated by our users from our Website</p>
                </div>
            </div>
            <!-- end col -->
        </div>
        <!-- end row -->

        <div class="row gallery-wrapper">
          
            @foreach ($images as $item)
              
            <div class="element-item col-xxl-3 col-xl-4 col-sm-6 photography" data-category="photography">
                <div class="gallery-box card">
                    <div class="gallery-container">
                        <a class="image-popup" href="{{ asset($item->image_url) }}" title="">
                            <img class="gallery-img img-fluid mx-auto" src="{{ asset($item->image_url) }}" alt="" />
                            <div class="gallery-overlay">
                                <h5 class="overlay-caption">{{$item->prompt}}</h5>
                            </div>
                        </a>
                    </div>

                    <div class="box-content">
                        <div class="d-flex align-items-center mt-1">
                            {{-- <div class="flex-grow-1 text-muted">by <a href="" class="text-body text-truncate">{{$item->user->name}}</a></div> --}}
                        </div>
                    </div>
                </div>
            </div>
            @endforeach
            <!-- end col -->
            
        </div>
        <!-- end row -->
        <div class="mx-auto d-flex justify-content-center">
            <a href="{{ route('ai.image.gallery') }}" class="btn gradient-btn-5">Show More</a>
        </div>
        
    </div>
</section>