<div class="col-lg-12">
    <div class="card">
      
        <div class="card-body">
            <div class="text-center mb-5">
                <h1 class="mb-3 ff-secondary fw-semibold lh-base">AI Image Gallery</h1>
                <p class="text-muted">Images generated by our users from our Website</p>
            </div>

            <!-- Swiper -->
            <div class="swiper effect-coverflow-swiper rounded pb-5">
                <div class="swiper-wrapper">
                    @foreach ($images_slider as $item)
                    <div class="swiper-slide">
                        <a class="image-popup" href="{{ $item->image_url }}" title="">
                            <img class="gallery-img img-fluid mx-auto" src="{{ $item->image_url }}" alt="" />
                        </a>
                    </div>
                    @endforeach
                </div>
                <div class="swiper-pagination swiper-pagination-dark"></div>
            </div>
        </div><!-- end card-body -->
    </div><!-- end card -->
</div><!--end col-->